version: '3.5'

services:
  sentinel:
    image: thebizark/docker-sentinel
    hostname: sentinel-dashboard
    container_name: sentinel-dashboard
    ports:
      - "8718:8718"
    environment:
      - JAVA_OPTS=-Dcsp.sentinel.log.dir=/opt/logs
    volumes:
      - ./logs:/opt/logs