version: '3.5'

services:
  sentinel:
    image: foxiswho/sentinel
    hostname: sentinel
    container_name: sentinel
    ports:
      - "8780:8080"
    environment:
      - JAVA_OPTS=-Dserver.port=8780 -Dcsp.sentinel.dashboard.server=localhost:8780 -Dcsp.sentinel.log.dir=/opt/logs -Dproject.name=sentinel-dashboard -Djava.security.egd=file:/dev/./urandom
    volumes:
      - ./logs:/opt/logs