version: '3.5'

services:
  sentinel:
    image: foxiswho/sentinel
    hostname: sentinel
    container_name: sentinel
    ports:
      - "8780:8080"
    environment:
      - JAVA_OPTS=-Dcsp.sentinel.log.dir=/opt/logs
    volumes:
      - ./logs:/opt/logs