version: '3.5'

services:
  sentinel:
    image: foxiswho/sentinel
    hostname: sentinel
    container_name: sentinel
    ports:
      - "8080:8080"
    #environment:
      #- JAVA_OPTS=-Xmx1g
    volumes:
      - ./logs:/opt/logs